import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import AptosProvider from '@/context/AptosProvider';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'VoiceLab',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body className={inter.className}>
                <AptosProvider> {children}</AptosProvider>
            </body>
        </html>
    );
}
