[package]
name = "voice_lab"
version = "1.0.0"
authors = []

[addresses]
owner = 'f5c7a683bb489bccc75a65c6759845b792ba177562b516143ab1dd892422c2a2'
voice_lab = '0d9bd23f9c94e6898d0305fb69d418b4cbc9668124d914a598510ad0358b90ce'

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosTokenObjects]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-token-objects"

[dev-dependencies]